//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMCUC.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicSession
    {
        public AcademicSession()
        {
            this.Students = new HashSet<Student>();
        }
    
        public System.Guid Id { get; set; }
        public string Session { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
    }
}
