//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMCUC.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int ID { get; set; }
        public string ModuleName { get; set; }
        public string Action { get; set; }
        public string Log { get; set; }
        public string user { get; set; }
        public Nullable<System.DateTime> actiondate { get; set; }
    }
}
