//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMCUC.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackupHistory
    {
        public int ID { get; set; }
        public string BackupBy { get; set; }
        public string FileName { get; set; }
        public System.DateTime BackupDate { get; set; }
    }
}
