//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMCUC.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.InitialPaymentDetails = new HashSet<InitialPaymentDetail>();
            this.Students = new HashSet<Student>();
        }
    
        public int Id { get; set; }
        public string CourseName { get; set; }
        public Nullable<decimal> CourseFee { get; set; }
    
        public virtual ICollection<InitialPaymentDetail> InitialPaymentDetails { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
