//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMCUC.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentOriginalDocument
    {
        public int Id { get; set; }
        public System.Guid StudentId { get; set; }
        public int OriginalDocumentId { get; set; }
    
        public virtual OriginalDocument OriginalDocument { get; set; }
        public virtual Student Student { get; set; }
    }
}
