//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMCUC.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.AcademicRecords = new HashSet<AcademicRecord>();
            this.Guardians = new HashSet<Guardian>();
            this.InitialPaymentDetails = new HashSet<InitialPaymentDetail>();
            this.Payments = new HashSet<Payment>();
            this.StudentOriginalDocuments = new HashSet<StudentOriginalDocument>();
        }
    
        public System.Guid Id { get; set; }
        public int StdID { get; set; }
        public string StdNameBangla { get; set; }
        public string StdNameEnglish { get; set; }
        public string StdFatherNameBangla { get; set; }
        public string StdFatherNameEnglish { get; set; }
        public string StdMotherNameBangla { get; set; }
        public string StdMotherNameEnglish { get; set; }
        public string PermanentAddress { get; set; }
        public string PresentAddress { get; set; }
        public string Picture { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Religion { get; set; }
        public string Nationality { get; set; }
        public string RegistrationNo { get; set; }
        public string ExamRollNo { get; set; }
        public Nullable<bool> IsSuspended { get; set; }
        public string SuspendedDesc { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int FormNo { get; set; }
        public Nullable<System.Guid> AcademicSessionId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> SemesterId { get; set; }
    
        public virtual ICollection<AcademicRecord> AcademicRecords { get; set; }
        public virtual AcademicSession AcademicSession { get; set; }
        public virtual Course Course { get; set; }
        public virtual ICollection<Guardian> Guardians { get; set; }
        public virtual ICollection<InitialPaymentDetail> InitialPaymentDetails { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual ICollection<StudentOriginalDocument> StudentOriginalDocuments { get; set; }
    }
}
